require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Layout/LineLength:
  Max: 300
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Exclude:
    - 'app/policies/*'

Style/Documentation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
  
Rails/HasManyOrHasOneDependent:
  Enabled: false
  
RSpec/InstanceVariable:
  Enabled: false
  
RSpec/MultipleExpectations:
  Enabled: false
  
RSpec/ExampleLength:
  Enabled: false
  
RSpec/LetSetup:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
